#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  16000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

// 如果使用 Duplex I2S 模式，请注释下面一行
#define AUDIO_I2S_METHOD_SIMPLEX

#ifdef AUDIO_I2S_METHOD_SIMPLEX

#define AUDIO_I2S_MIC_GPIO_WS   GPIO_NUM_4
#define AUDIO_I2S_MIC_GPIO_SCK  GPIO_NUM_5
#define AUDIO_I2S_MIC_GPIO_DIN  GPIO_NUM_6
#define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_7
#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_15
#define AUDIO_I2S_SPK_GPIO_LRCK GPIO_NUM_16

#else

#define AUDIO_I2S_GPIO_WS GPIO_NUM_4
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_5
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_6
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_7

#endif


#define BUILTIN_LED_GPIO        GPIO_NUM_20
#define BOOT_BUTTON_GPIO        GPIO_NUM_0
#define TOUCH_BUTTON_GPIO       GPIO_NUM_9
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_40
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_38
#define PAGE_DOWN_BUTTON_GPIO   GPIO_NUM_17
#define PAGE_UP_BUTTON_GPIO     GPIO_NUM_47 
 
#define DISPLAY_SDA_PIN GPIO_NUM_12
#define DISPLAY_SCL_PIN GPIO_NUM_11
#define DISPLAY_WIDTH   128

#if CONFIG_OLED_SSD1306_128X32
#define DISPLAY_HEIGHT  32
#elif CONFIG_OLED_SSD1306_128X64
#define DISPLAY_HEIGHT  64
#elif CONFIG_OLED_SH1106_128X64
#define DISPLAY_HEIGHT  64
#define SH1106
#else
#error "未选择 OLED 屏幕类型"
#endif

#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y true

#define POWER_GPIO   GPIO_NUM_45

#define MAX30102_I2C_PORT     I2C_NUM_1
#define MAX30102_I2C_SDA_PIN  GPIO_NUM_21
#define MAX30102_I2C_SCL_PIN  GPIO_NUM_14
#define MAX30102_I2C_ADDR           0x57 /*!< max30102 i2c 地址 */

// MPU6050 软件I2C引脚配置
#define MPU6050_SDA_PIN  GPIO_NUM_42
#define MPU6050_SCL_PIN  GPIO_NUM_41

// PAJ7620 software I2C uses free general-purpose pins that avoid the current
// board peripherals, USB, console UART, and strapping pins.
#define PAJ7620_SDA_PIN  GPIO_NUM_45
#define PAJ7620_SCL_PIN  GPIO_NUM_38
#define PAJ7620_INT_PIN  GPIO_NUM_NC

// A MCP Test: Control a lamp
#define LAMP_GPIO GPIO_NUM_48

#endif // _BOARD_CONFIG_H_
